name: CI

on:
  push:
    paths: ['**.luau', '**.lua', '**.rbxm', '**.json', '**.yml', '**.toml', 'wally.lock']
  pull_request:
    paths: ['**.luau', '**.lua', '**.rbxm', '**.json', '**.yml', '**.toml', 'wally.lock']

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: fluent-zenith-ci-${{ github.sha }}
